name: address_entity_extraction

channels:
  - esri
  - conda-forge

dependencies:
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - python=3.9
  - pyarrow
  - seaborn
  - pip:
    - autodocsumm
    - build
    - bump2version
    - furo
    - nbsphinx
    - spacy
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - tox
    - tox-conda
    - twine
